
  <div class="all-credits">

    <div class="credits">

   <h2>Image Credits</h2>

   <p>The images in this outcome were sourced from..</p>
<ul>
<li><a class="credits" href="https://www.svgrepo.com/">SVG Repo</a></li>
<li><a class="credits" href="https://pixabay.com/">Pixabay</a></li>
</ul>

<p>Other images were generated using <a class="credits" href="https://chatgpt.com/">ChatGPT</a> / <a class="credits" href="https://gemini.google.com/app?hl=en_GB">Gemini</a> and, most often were further edited in GIMP.</p>

<br>

<hr>

    <h2>Text Credits / Disclaimer</h2>

    <p>The data for this outcome was generated by ChatGPT.  It is fairly accurate but may contain mistakes.</p>

    </div>  <!--  / error box -->

<div class='center-image'>
    <img class='error-image' src="images/credits.png" alt="Credits cartoon" >
 </div>  <!-- / center-image -->

</div>  <!-- / no results message -->